import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
// import { SessionProvider } from "next-auth/react";
import { Providers } from "@/components/Providers";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.className}>
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
